version: "3.8"
services:
  mariadb:
    image: mariadb:10.6.4
    environment:
      - MARIADB_ROOT_PASSWORD=password
    ports:
      - "4306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  mariadb-data: {}
